### ISSUE TITLE
InnovaSpy-packages

### ISSUE THREAD

**Issue by InnovaSpy** [InnovaSpy/mobile-phone-spy-apps#1]
InnovaSPY is a cell phone tracking and monitoring software for iPhone and Android smartphones and tablets. Once installed on the device you will be able to monitor and record all calls made and received, real time GPS location of the mobile phone, track and record text messages (SMS), have access to the entire contacts list and media files stored on the cell phone and much more. The InnovaSPY application satisfies all needs for monitoring, tracking, protecting and backing up the data of any smartphone.

**Comment by beyondnova** [comment]
No files shared ...?
